from typing import Any, Protocol

from llvmlite import ir

from compiler.target import TargetSpec


class CodegenContext(Protocol):
    target: TargetSpec
    module: ir.Module
    builder: ir.IRBuilder
    func: ir.Function
    vars: dict[str, tuple[Any, str]]
    fn_decls: dict[str, Any]
    closure_env_types: dict[int, ir.LiteralStructType]
    iface_vtables: dict[tuple[str, str], ir.GlobalVariable]
    iface_thunks: dict[tuple[str, str, str], ir.Function]
    function_value_thunks: dict[str, ir.Function]
    defer_sites: list[Any]
    defer_stack_slot: Any
    defer_top_slot: Any
    emitting_defer: bool
    current_gc_mark: Any
    current_return_slot: Any
    current_error_slot: Any
    current_is_fallible: bool
    current_return_type: str
    current_is_main: bool
    printf: ir.Function | None
    fprintf: ir.Function | None
    exit_fn: ir.Function | None
    nc_stderr: ir.Function | None
    malloc: ir.Function | None
    gc_alloc: ir.Function | None
    gc_collect: ir.Function | None
    gc_live: ir.Function | None
    gc_init: ir.Function | None
    gc_root_mark: ir.Function | None
    gc_root_rewind: ir.Function | None
    gc_push_root_slot: ir.Function | None
    str_cat_fn: ir.Function | None
    str_slice_fn: ir.Function | None
    i32_to_str_fn: ir.Function | None
    i64_to_str_fn: ir.Function | None
    u64_to_str_fn: ir.Function | None
    f64_to_str_fn: ir.Function | None
    rune_to_str_fn: ir.Function | None
    str_to_i32_fn: ir.Function | None
    cstr_to_str_fn: ir.Function | None
    map_init_fn: ir.Function | None
    map_get_fn: ir.Function | None
    map_set_fn: ir.Function | None
    map_has_fn: ir.Function | None
    map_delete_fn: ir.Function | None
    map_clear_fn: ir.Function | None
    map_next_fn: ir.Function | None
    slice_copy_fn: ir.Function | None
    slice_append_fn: ir.Function | None
    slice_copy_into_fn: ir.Function | None
    slice_clear_fn: ir.Function | None
    os_set_args_fn: ir.Function | None
    sprintf: ir.Function | None
    atoi: ir.Function | None
    memcmp: ir.Function | None
    empty_c_string: Any
    strings: dict[tuple[str, str], ir.GlobalVariable]
    map_descs: dict[str, ir.GlobalVariable]
    map_hash_fns: dict[str, ir.Function]
    map_eq_fns: dict[str, ir.Function]

    def alloca_at_entry(self, name: str, typ: ir.Type) -> ir.AllocaInstr: ...
    def root_slots_for_type(self, ptr: Any, nc_type: str): ...
    def value_to_stack_ptr(self, value: Any, typ: Any, name: str): ...
    def malloc_bytes(self, count: Any): ...
    def copy_bytes(self, dest: Any, dest_offset: Any, source: Any, source_offset: Any, count: Any, label: str): ...
    def sizeof_type(self, nc_type: str) -> int: ...
    def alignof_type(self, nc_type: str) -> int: ...
    def cast_to(self, value: Any, nc_type: str): ...
    def emit_expr(self, expr: Any): ...
    def emit_stmt(self, stmt: Any): ...
    def emit_block(self, block: Any): ...
    def emit_coerced_expr(self, expr: Any, target_type: str): ...
    def emit_lvalue(self, expr: Any): ...
    def emit_binary_values(self, left: Any, op: str, right: Any, typ: str): ...
    def emit_str_cat(self, left: Any, right: Any): ...
    def emit_map_has(self, map_expr: Any, key_expr: Any): ...
    def emit_iface_method_call(self, node: Any): ...
    def value_to_i8_stack_ptr(self, value: Any, typ: Any, name: str): ...
    def align_to(self, value: int, alignment: int) -> int: ...
    def aligned_sizeof_type(self, nc_type: str) -> int: ...
    def sizeof_fields(self, fields: list[str]) -> int: ...
    def ensure_memcmp(self): ...
    def ensure_ncrt_runtime(self): ...
    def ensure_sprintf(self): ...
    def slice_value(self, elem_type: str, ptr: Any, length: Any, cap: Any): ...
    def init_defer_state(self): ...
    def init_gc_frame(self, is_main: bool = False): ...
    def init_os_args(self, argc: Any, argv: Any): ...
    def emit_deferred(self): ...
    def emit_gc_rewind(self): ...
    def emit_print_error(self, value: Any): ...
    def emit_exit(self, code: int): ...
    def empty_string_ptr(self): ...
    def fallible_out_slots(self, success_type: str): ...
    def emit_fallible_method_call_raw(self, node: Any): ...
