from typing import Any, Protocol

from llvmlite import ir

from compiler.target import TargetSpec


class CodegenContext(Protocol):
    target: TargetSpec
    module: ir.Module
    builder: ir.IRBuilder
    func: ir.Function
    gc_alloc: ir.Function | None
    str_cat_fn: ir.Function | None
    i32_to_str_fn: ir.Function | None
    i64_to_str_fn: ir.Function | None
    u64_to_str_fn: ir.Function | None
    f64_to_str_fn: ir.Function | None
    rune_to_str_fn: ir.Function | None
    str_to_i32_fn: ir.Function | None
    cstr_to_str_fn: ir.Function | None
    map_init_fn: ir.Function | None
    map_get_fn: ir.Function | None
    map_set_fn: ir.Function | None
    map_has_fn: ir.Function | None
    map_delete_fn: ir.Function | None
    map_descs: dict[str, ir.GlobalVariable]
    map_hash_fns: dict[str, ir.Function]
    map_eq_fns: dict[str, ir.Function]

    def alloca_at_entry(self, name: str, typ: ir.Type) -> ir.AllocaInstr: ...
    def root_slots_for_type(self, ptr: Any, nc_type: str): ...
    def value_to_stack_ptr(self, value: Any, typ: Any, name: str): ...
    def malloc_bytes(self, count: Any): ...
    def copy_bytes(self, dest: Any, dest_offset: Any, source: Any, source_offset: Any, count: Any, label: str): ...
    def sizeof_type(self, nc_type: str) -> int: ...
    def alignof_type(self, nc_type: str) -> int: ...
    def cast_to(self, value: Any, nc_type: str): ...
    def emit_expr(self, expr: Any): ...
    def emit_coerced_expr(self, expr: Any, target_type: str): ...
    def emit_lvalue(self, expr: Any): ...
    def emit_binary_values(self, left: Any, op: str, right: Any, typ: str): ...
    def emit_str_cat(self, left: Any, right: Any): ...
    def value_to_i8_stack_ptr(self, value: Any, typ: Any, name: str): ...
    def align_to(self, value: int, alignment: int) -> int: ...
    def ensure_memcmp(self): ...
    def ensure_ncrt_runtime(self): ...
    def ensure_sprintf(self): ...
    def slice_value(self, elem_type: str, ptr: Any, length: Any, cap: Any): ...
